### ISSUE TITLE
In OSX kicommand folder must be located in two locations by default

### ISSUE THREAD

**Issue by Thingable** [HiGregSmith/KiCommand#1]
To get the plugin to run I had to place the folder in both '/Applications/Kicad/kicad.app/Contents/SharedSupport/scripting/plugins' and a folder that I created in '/Users/*username*/kicad'.

**Comment by HiGregSmith** [comment]
I think this is correct. I use the ~/kicad folder to store user commands and current state. There is probably a better way to do this, but let me know if this is an actual problem.
