### ISSUE TITLE
Issue with the command line input on kicad 5.1.5

### ISSUE THREAD

**Issue by GustavoLafava** [HiGregSmith/KiCommand#5]
![Screenshot_20200304_120327](https://user-images.githubusercontent.com/4705483/75873644-8c075580-5e10-11ea-81bf-1f37289653c6.png)

This error appear after importing the plugin (actual git master clone version).  The command line appear as you could see in the following image and it's impossibile to use (no command could be executed).

![Screenshot_20200304_121118](https://user-images.githubusercontent.com/4705483/75874087-5616a100-5e11-11ea-9ab2-c4df8027dfde.png)

Application: KiCad
Version: 5.1.5+dfsg1-2, release build
Libraries:
    wxWidgets 3.0.4
    libcurl/7.67.0 OpenSSL/1.1.1d zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.40.0 librtmp/2.3
Platform: Linux 5.4.0-4-amd64 x86_64, 64 bit, Little endian, wxGTK
Build Info:
    wxWidgets: 3.0.4 (wchar_t,wx containers,compatible with 2.8) GTK+ 3.24
    Boost: 1.67.0
    OpenCASCADE Technology: 7.3.0
    Curl: 7.66.0
    Compiler: GCC 9.2.1 with C++ ABI 1013

Build settings:
    USE_WX_GRAPHICS_CONTEXT=OFF
    USE_WX_OVERLAY=ON
    KICAD_SCRIPTING=ON
    KICAD_SCRIPTING_MODULES=ON
    KICAD_SCRIPTING_PYTHON3=ON
    KICAD_SCRIPTING_WXPYTHON=ON
    KICAD_SCRIPTING_WXPYTHON_PHOENIX=ON
    KICAD_SCRIPTING_ACTION_MENU=ON
    BUILD_GITHUB_PLUGIN=ON
    KICAD_USE_OCE=OFF
    KICAD_USE_OCC=ON
    KICAD_SPICE=ON

**Comment by HiGregSmith** [comment]
It looks like something in wxpython changed. Try removing that part of the if statement containing _wxPyDeadObject. I'll see if I can find a replacement or find out where that object moved to.

Please let me know the results of testing with Python3, I haven't been able to test it.

**Comment by HiGregSmith** [comment]
Latest update checks for the existence of _wxPyDeadObject before using it. I also fixed the print functions in the test suite to be Python3 compatible. Please report any trouble running KiCommand or the test suite with python 3. To run the test suite, open the Script Console and run "import kicommand.test".

**Comment by GustavoLafava** [comment]
Sorry for the delay, now it show the prompt nicely.
I tried to use

>>> import kicommand.test

to run the test on the scripting console, but it terminate without print any output.

**Comment by HiGregSmith** [comment]
Do either of the following commands in the Python Script Console reveal anything?

(precede by "import pcbnew")

> pcbnew.GetUnLoadableWizards()
> pcbnew.GetWizardsBackTrace()

**Comment by GustavoLafava** [comment]
>import pcbnew
>pcbnew.GetUnLoadableWizards()

'Skip subdir /usr/share/kicad/scripting/plugins/__pycache__\nSkip subdir /home/lafava/.kicad/scripting/plugins\nSkip subdir /home/lafava/.kicad/scripting/plugins/KiCommand'

>pcbnew.GetWizardsBackTrace()

''

**Comment by HiGregSmith** [comment]
Ok. This seems to indicate KiCommand has a problem loading. Try in the Scripting Console:

> import kicommand

And let me know the results, please.

**Comment by GustavoLafava** [comment]
Nothing appears using the import command in the scripting console, but if I load kicommand from the "external plugins" menù, a working prompt appear with an error "Warning! Expected Pad Shapes are different than KiCommand expects. KiCAD has been updated? Consider running unit tests (import kicommand.test)".

**Comment by HiGregSmith** [comment]
What happens if you type a KiCommand string at the top of that window? Try (without quotes) “123 int print”

**Comment by GustavoLafava** [comment]
>123 
>1 operands left on the stack.

**Comment by HiGregSmith** [comment]
Perfect. I think it’s working. Do you need some help getting started?

**Comment by HiGregSmith** [comment]
Can you help me debug the “import kicommand.test” issue. When you type that in the Python Script Console, it should output at least something.

**Comment by GustavoLafava** [comment]
Sure, but the only output it gave me the first time is a error because the data dir ~/kicad/kicommand didn't exist.

![Screenshot_20200305_104756](https://user-images.githubusercontent.com/4705483/75969183-d64f0c00-5ece-11ea-9f44-b776cf9abf5a.png)

**Comment by HiGregSmith** [comment]
Can you create that directory “~/kicad/kicommand”? That’s where it stores user commands for now.

**Comment by GustavoLafava** [comment]
Yes, I created it to remove the error, but no file in here for now. I haven't any idea how to help you..
The test command report have to appear on the scripting console or on the "prompt" window?

KiCommand files are in ~/.kicad/scripting/plugins/kicommand, a symbolic link to ~/.kicad/scripting/plugins/KiCommand/kicommand

**Comment by HiGregSmith** [comment]
The test output is largely in the Scripting Console. It should run about 96 tests and at the end it should say “OK”.

Have you been able to run some KiCommand commands in the main window?

**Comment by GustavoLafava** [comment]
Ok, I try to run this command after selecting a text on the dwgs.user layer.
> toptextobj selected Dwgs.User texttosegments F.Cu tocopper

but no segments are present on the copper layer
> pads setselect 

works fine

**Comment by GustavoLafava** [comment]
Sometime start kicommand from External Plugins cause kicad to crash

>  [9]+  Segmentation fault      kicad

**Comment by HiGregSmith** [comment]
There have been several updates to KiCommand. Is this still an issue? If so, are you able to recreate it?
